language: node_js
node_js:
- '4.2'
env:
- CXX=g++-4.8
addons:
  code_climate:
    repo_token: 7d98e7ec50f31db030a3ade804d34812c8837a047f96020f609a4d168bc958ff
deploy:
  provider: heroku
  app: awesome-vr
  api_key:
    secure: BdlXSIt70aXQzq+QLxbxcILXRkbZp5IKFlsAaM7oQ0f50ZRIQOOIAqct1jQk3HfLZ1mRueljS8NCTRMmFBYM/55B2dyxxPouXWNh83dA32vGCC36DxnXn72i9yMqJbi6NZ4qH3qUmglNe6vDd5MyeS56jEbGpQ/dtxfRv/08lQYPUpdnh7d1S01rorl1qaFedkHt7hrpwKTxJMuhEcXIz4LaZ/a8fy8oBtfcKcOtRp9XUtwHp3PNrejNRMubAH0zF0dT/aqSJXir7+hLLAhsvqugb1rq3Y0nBF/C/S3bHhxMuqPrLCgGYIBpJGgE574IWqthH51YQQujUJnwmc/W1tXW0GIUv9KAcRrj+TI6dQ52/d8vQyy6qIc4xdLW4z7JuULAoDPwo4cqj8dyHLD2JWeGlfABHN8R70VTGq/CLC2TUH4Z4FLWshXFT73viraoRh+t0oj1AmPFz5v0ngDGST7MzplO4nsl86xoVq3nQUQFqah2YV5Dkxkr8jUGm5eh4vFww5x7SfOWZAzc37U/LxgsjWtLFJceHJ+p/99yQ3LoqwUT/GddlWRudQ9vpx08j4ChqMv4XkwvmPnwyvFORxmN3n4diH79tDYggDRZTroBFJEK3o0ZFC6YShjz90jkhhQyCvvXTvXI2JY20qNYBLyrC4pEpJ5bsdKCQkma+tE=
after_success:
- npm install codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
